In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Aqram_Project1_FinalClean_data.csv')

In [4]:
df.head()

MS SubClass  Lot Frontage  Lot Area  Street  Lot Shape  Land Slope  \
0           20         141.0     31770       1          1           0   
1           20          80.0     11622       1          0           0   
2           20          81.0     14267       1          1           0   
3           20          93.0     11160       1          0           0   
4           60          74.0     13830       1          1           0   

   Overall Qual  Overall Cond  Year Built  Year Remod/Add  ...  \
0             6             5        1960            1960  ...   
1             5             6        1961            1961  ...   
2             6             6        1958            1958  ...   
3             7             5        1968            1968  ...   
4             5             5        1997            1998  ...   

   Sale Type_ConLw  Sale Type_New  Sale Type_Oth  Sale Type_VWD  \
0                0              0              0              0   
1                0              0              0              0   
2                0              0              0              0   
3                0              0              0              0   
4                0              0              0              0   

   Sale Type_WD   Sale Condition_AdjLand  Sale Condition_Alloca  \
0              1                       0                      0   
1              1                       0                      0   
2              1                       0                      0   
3              1                       0                      0   
4              1                       0                      0   

   Sale Condition_Family  Sale Condition_Normal  Sale Condition_Partial  
0                      0                      1                       0  
1                      0                      1                       0  
2                      0                      1                       0  
3                      0                      1                       0  
4                      0                      1                       0  

[5 rows x 210 columns]

In [7]:
X = df.drop('SalePrice', axis = 1)
y = df['SalePrice']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
from sklearn.linear_model import LassoCV

In [24]:
lasso_cv_model = LassoCV(eps = 0.1, n_alphas = 100, cv = 5)

In [25]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [26]:
lasso_cv_model.alpha_

5626.778928688413

In [27]:
test_predictions = lasso_cv_model.predict(X_test)

In [28]:
from sklearn.metrics import mean_squared_error

In [29]:
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [30]:
MSE

668832706.7073733

In [31]:
RMSE

25861.800144370718

In [32]:
lasso_cv_model.coef_

array([   -0.        ,   327.74996857,    21.49908712,     0.        ,
           0.        ,     0.        , 17981.82569432,     0.        ,
        3151.83271868,   887.74749803,     0.        ,  6282.81343739,
           0.        ,  1127.18075207,     0.        ,  1134.90360812,
           0.        ,  7859.12263501,     0.        ,     0.        ,
          -0.        ,  4366.86843443,     0.        ,     0.        ,
        3119.74648954,     0.        ,    -0.        , 17501.24777273,
           0.        ,    -0.        ,     0.        ,     0.        ,
          -0.        ,    -0.        ,  5479.77183389,     0.        ,
           0.        ,  2262.14802734,     0.        ,  1315.62061552,
         943.22680016,  4939.07441859,     0.        ,     0.        ,
           0.        ,     0.        ,     0.        ,    -0.        ,
           0.        ,     0.        ,     0.        ,     0.        ,
           0.        ,    -0.        ,    -0.        ,     0.        ,
      

In [38]:
x = lasso_cv_model.coef_
x[x>0]

array([  327.74996857,    21.49908712, 17981.82569432,  3151.83271868,
         887.74749803,  6282.81343739,  1127.18075207,  1134.90360812,
        7859.12263501,  4366.86843443,  3119.74648954, 17501.24777273,
        5479.77183389,  2262.14802734,  1315.62061552,   943.22680016,
        4939.07441859,  1532.83142653,  1472.0979229 ])

In [35]:
print(np.where(np.isclose(x, 327.74996857)), np.where(np.isclose(x, 21.49908712)), np.where(np.isclose(x, 17981.82569432)),
np.where(np.isclose(x, 3151.83271868)), np.where(np.isclose(x, 887.74749803)), np.where(np.isclose(x, 6282.81343739)),
np.where(np.isclose(x, 1127.18075207)), np.where(np.isclose(x, 1134.90360812)), np.where(np.isclose(x, 7859.12263501)),
np.where(np.isclose(x, 4366.86843443)), np.where(np.isclose(x, 3119.74648954)), np.where(np.isclose(x, 17501.24777273)),
np.where(np.isclose(x, 5479.77183389)), np.where(np.isclose(x, 2262.14802734)), np.where(np.isclose(x, 1315.62061552)),
np.where(np.isclose(x, 943.22680016)),np.where(np.isclose(x, 4939.07441859)),np.where(np.isclose(x, 1532.83142653)),
np.where(np.isclose(x, 1472.0979229)))

(array([1], dtype=int64),) (array([2], dtype=int64),) (array([6], dtype=int64),) (array([8], dtype=int64),) (array([9], dtype=int64),) (array([11], dtype=int64),) (array([13], dtype=int64),) (array([15], dtype=int64),) (array([17], dtype=int64),) (array([21], dtype=int64),) (array([24], dtype=int64),) (array([27], dtype=int64),) (array([34], dtype=int64),) (array([37], dtype=int64),) (array([39], dtype=int64),) (array([40], dtype=int64),) (array([41], dtype=int64),) (array([87], dtype=int64),) (array([208], dtype=int64),)


In [40]:
arr = X.columns.values
print(arr[1] + ',' + arr[2] + ',' + arr[6] + ',' + arr[8] + ',' + arr[9] + ',' + arr[11] + ','
     + arr[13] + ',' + arr[15] + ',' + arr[17] + ',' + arr[21] + ',' + arr[24] + ',' 
     + arr[27] + ',' + arr[34] + ',' + arr[37] + ',' + arr[39] + ',' + arr[40] + ',' + arr[41] + 
     ',' + arr[87] + ',' + arr[208])

Lot Frontage,Lot Area,Overall Qual,Year Built,Year Remod/Add,Exter Qual,Bsmt Qual,Bsmt Exposure,BsmtFin SF 1,Total Bsmt SF,1st Flr SF,Gr Liv Area,Kitchen Qual,Fireplace Qu,Garage Finish,Garage Cars,Garage Area,Neighborhood_NridgHt,Sale Condition_Partial
